# Generated by Django 3.2 on 2021-05-29 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_contactus_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
    ]
